### ISSUE TITLE
timeline for 2.0.0 release

### ISSUE THREAD

**Issue by macneib** [mgol/grunt-ng-annotate#41]
Hi thanks for all your work on this project!
Was curious about when ~2.0.0 would be available on npm?  npm currently show 1.0.1 available.

**Comment by mgol** [comment]
Good question! Current `master` is bumped to `2.0.0-pre` because I dropped official Node 0.10 support, that's the only reason. Since there are no new fixes or new features on `master` compared to `1.0.1` so far, I don't feel the need to release at the moment. If something appears (e.g. someone fixes [one of the issues](https://github.com/mgol/grunt-ng-annotate/issues)) then I'll definitely release!

**Comment by macneib** [comment]
ok makes sense. I ask because the ng-annotate 1.2.0 handles angular.module('foo').component feature in angular 1.5.x, whereas ng-annotate 1.0.0 doesn't appear to.  It's not a big deal. I'm just pulling straight from grunt-ng-annotate master for now, but I just wanted to set a reminder to check in on this.
Cheers

**Comment by mgol** [comment]
What you described doesn't have anything to do with `grunt-ng-annotate`. The latest stable release, `1.0.1` depends on `"ng-annotate": "^1.0.0"` which means it picks up the latest `1.x.y` release of `ng-annotate`, including `1.2.0`. You don't need to install anything from `master`, just install the regular version and it'll work fine.
