### ISSUE TITLE
ng-Annotate

### ISSUE THREAD

**Issue by science162** [mgol/grunt-ng-annotate#59]
after running yo angular:route popular,
I run grunt build but it  run into error 

here is the error

![capture5](https://user-images.githubusercontent.com/17831826/29334234-07f65cce-8207-11e7-81d9-14155105a3fc.PNG)

And here is my script.js file

```js
.when('/popular', {
  templateUrl: 'views/popular.html',
  controller: 'PopularCtrl',
  controllerAs: 'popular'
})
'use strict';
/**
 * @ngdoc overview
 * @name cineAngularApp
 * @description
 * # cineAngularApp
 *
 * Main module of the application.
 */
angular
  .module('cineAngularApp', []);

'use strict';

/**
 * @ngdoc function
 * @name cineAngularApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the cineAngularApp
 */
angular.module('cineAngularApp')
  .controller('MainCtrl', function () {
    this.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
  });

'use strict';
/**
 * @ngdoc function
 * @name cineAngularApp.controller:PopularCtrl
 * @description
 * # PopularCtrl
 * Controller of the cineAngularApp
 */
angular.module('cineAngularApp')
  .controller('PopularCtrl', function () {
    this.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
  });
```

**Comment by mgol** [comment]
Pleas wrap the code snippet in triple backticks as I described in https://github.com/mgol/grunt-ng-annotate/issues/45#issuecomment-322563828. It's hard to read it otherwise.

**Comment by science162** [comment]
Oh ok sorry here it is 
```js
.when('/popular', {
templateUrl: 'views/popular.html',
controller: 'PopularCtrl',
controllerAs: 'popular'
})
'use strict';
/**

    @ngdoc overview
    @name cineAngularApp
    @description
    cineAngularApp
    Main module of the application.
    */
    angular
    .module('cineAngularApp', []);

'use strict';

/**

    @ngdoc function
    @name cineAngularApp.controller:MainCtrl
    @description
    MainCtrl
    Controller of the cineAngularApp
    */
    angular.module('cineAngularApp')
    .controller('MainCtrl', function () {
    this.awesomeThings = [
    'HTML5 Boilerplate',
    'AngularJS',
    'Karma'
    ];
    });

'use strict';
/**

    @ngdoc function
    @name cineAngularApp.controller:PopularCtrl
    @description
    PopularCtrl
    Controller of the cineAngularApp
    */
    angular.module('cineAngularApp')
    .controller('PopularCtrl', function () {
    this.awesomeThings = [
    'HTML5 Boilerplate',
    'AngularJS',
    'Karma'
    ];
    });

```

**Comment by mgol** [comment]
I edited your original post, you didn't have to post a new comment, you could have edited it as well. Also, I had to edit it to see the screenshot as you wrapped it in backticks so no image was shown. Please always look at the issue/comment after posting and edit it if there's an obvious mistake, I was confused about the missing error for a while.

Are those the whole contents of scripts.js? This is not valid JavaScript as it can't start with a dot, there has to be something before it? If not, that's why it's failing.

What versions of grunt-ng-annotate & ng-annotate do you have installed? `npm ls ng-annotate` & `npm ls grunt-ng-annotate` invoked in a terminal will tell you that if you don't know.

**Comment by science162** [comment]
ng-annotate@0.15.4
grunt-ng-annotate@0.902

the fact is that it is a project whith many JS file but the one with is involve in the error is the script.js above .
the error is about the line 1 some unexpected things. 
That bloc apear after running command
**yo angular : route popular** .
Then when I run **grunt build** , il show some error in script.js about the line 1.
It seems like the **yo angular : route popular** doesn't build the complete code to complete the route; it is just an intuition.

![capture5](https://user-images.githubusercontent.com/17831826/29336586-96f3239c-820e-11e7-88ed-ba9ecc7d1991.PNG)

**Comment by mgol** [comment]
If you pasted the whole contents of `script.js` then it's not valid JavaScript syntax as it can't start with a dot. Therefore, it's failing correctly. If you have the problem out of the box when using this generator then the problem lies in the generator; it shouldn't be passing invalid files to ng-annotate.
